on:
  create:
    tags:
      - v*

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "@foo:registry=https://${{secrets.GITLAB_PKG_URL}}/npm/" >> ~/.npmrc
          echo "//${{secrets.GITLAB_PKG_URL}}/npm/:_authToken=${{secrets.GITLAB_ACCESS_TOKEN}}" >> ~/.npmrc
      - run: |
          for folder in unity/Assets/org.nuget.*/
          do
            cd $folder
            cp package.json temp.json
            jq ".author.name=\"NuGet Gallery\"" temp.json > package.json
            cp package.json temp.json
            jq ".author.email=\"andtechstudios@gmail.com\"" temp.json > package.json
            cp package.json temp.json
            jq ".author.url=\"https://github.com/andtechstudios\"" temp.json > package.json
            cp package.json temp.json
            jq ".publishConfig.registry=\"https://${{secrets.GITLAB_PKG_URL}}/npm/\"" temp.json > package.json
            rm temp.json
            npm publish || echo -e '\e[33;1m[Warning] '$folder' was not published!\e[37;1m'
            cd -
          done
